"""add player_name_overrides to users

Revision ID: 12baff3d6136
Revises: a3c9f1b8e24d
Create Date: 2026-08-19 21:18:57.458968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12baff3d6136'
down_revision: Union[str, Sequence[str], None] = 'a3c9f1b8e24d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('player_name_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'player_name_overrides')
    # ### end Alembic commands ###
