"""initial schema

Revision ID: 561fc4bdb3e3
Revises: 
Create Date: 2026-06-10 10:55:13.435794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '561fc4bdb3e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_dataset_pool',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('apple_sub', sa.String(), nullable=True),
    sa.Column('google_sub', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apple_sub'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_table('careers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_team_name', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('draft_pool_type', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('completed_seasons', sa.Integer(), nullable=False),
    sa.Column('retention_limit', sa.Integer(), nullable=True),
    sa.Column('status_message', sa.String(), nullable=True),
    sa.Column('state_blob', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_careers_user_name')
    )
    op.create_table('entitlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_key', sa.String(), nullable=False),
    sa.Column('store_transaction_id', sa.String(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_key', name='uq_entitlements_user_product')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('store', sa.String(), nullable=True),
    sa.Column('store_transaction_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('round_num', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('team1_name', sa.String(), nullable=False),
    sa.Column('team2_name', sa.String(), nullable=False),
    sa.Column('toss_winner', sa.String(), nullable=True),
    sa.Column('toss_decision', sa.String(), nullable=True),
    sa.Column('result_summary', sa.String(), nullable=True),
    sa.Column('winner_name', sa.String(), nullable=True),
    sa.Column('team1_score', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('team2_score', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('motm_player_id', sa.UUID(), nullable=True),
    sa.Column('played_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('season_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('champion', sa.String(), nullable=True),
    sa.Column('runner_up', sa.String(), nullable=True),
    sa.Column('mvp_player_id', sa.UUID(), nullable=True),
    sa.Column('points_table', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('batting_leaderboard', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bowling_leaderboard', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('playoff_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_id', 'season_year', name='uq_season_history_career_year')
    )
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_user_team', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('runs_scored', sa.Integer(), nullable=False),
    sa.Column('balls_faced', sa.Integer(), nullable=False),
    sa.Column('runs_conceded', sa.Integer(), nullable=False),
    sa.Column('balls_bowled', sa.Integer(), nullable=False),
    sa.Column('captain_player_id', sa.UUID(), nullable=True),
    sa.Column('vice_captain_player_id', sa.UUID(), nullable=True),
    sa.Column('saved_presets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_id', 'name', name='uq_teams_career_name')
    )
    op.create_table('match_balls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('innings', sa.Integer(), nullable=False),
    sa.Column('over_num', sa.Integer(), nullable=False),
    sa.Column('ball_num', sa.Integer(), nullable=False),
    sa.Column('batter_id', sa.UUID(), nullable=True),
    sa.Column('bowler_id', sa.UUID(), nullable=True),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('wicket', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('commentary', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('base_ovr', sa.Integer(), nullable=False),
    sa.Column('batting_ovr', sa.Integer(), nullable=False),
    sa.Column('bowling_ovr', sa.Integer(), nullable=False),
    sa.Column('is_overseas', sa.Boolean(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('batting_hand', sa.String(), nullable=False),
    sa.Column('bowling_hand', sa.String(), nullable=False),
    sa.Column('batting_archetype', sa.String(), nullable=False),
    sa.Column('bowling_phase', sa.String(), nullable=False),
    sa.Column('bowling_type', sa.String(), nullable=False),
    sa.Column('strengths', sa.String(), nullable=True),
    sa.Column('weaknesses', sa.String(), nullable=True),
    sa.Column('preferred_position', sa.Integer(), nullable=False),
    sa.Column('form', sa.Float(), nullable=False),
    sa.Column('intent', sa.String(), nullable=False),
    sa.Column('season_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_season_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mvp_score', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_id', 'player_id', 'season_year', name='uq_player_season_stats')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_season_stats')
    op.drop_table('players')
    op.drop_table('match_balls')
    op.drop_table('teams')
    op.drop_table('season_history')
    op.drop_table('matches')
    op.drop_table('subscriptions')
    op.drop_table('entitlements')
    op.drop_table('careers')
    op.drop_table('users')
    op.drop_table('player_dataset_pool')
    # ### end Alembic commands ###
