#!/usr/bin/env python3
"""One-time IP-safe rename: real IPL franchises + players -> fictional.

Single source of truth + audit record for the rename so every surface (engine
constants, players_data rosters, the two player CSVs, mobile theme, webapp,
tests) stays consistent.

- TEAM_MAP / ABBR_MAP: applied to all text files by `apply_team_renames`.
- PLAYER_MAP: the real->fictional player names. The CSV transform (names +
  generic IP-free bios) was produced externally and validated (ratings, ages,
  slots, and roles are byte-identical to the originals; no real player/team/
  nationality references remain). `apply_player_roster_renames` re-applies the
  same names to the 2026 roster lists in players_data.py.

Player names follow an initial-preserving convention (keep the first letters of
the first and last names; alter interior letters), so abbreviated scorecard
forms like "V. Kohli" stay familiar as "V. Kuhli" while the full name is
legally distinct. Users can rename anyone via the in-app roster editor.

Usage:
    python scripts/ip_safe_rename.py --check    # print mappings, change nothing
    python scripts/ip_safe_rename.py --apply    # re-apply team + roster renames
"""
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENGINE = ROOT / "packages" / "sim_engine" / "src" / "cricket_sim_engine"

# --- Team mapping (real -> fictional). Keep the city; invent the rest. --------
TEAM_MAP = {
    "Chennai Super Kings": "Chennai Cholas",
    "Mumbai Indians": "Mumbai Mavericks",
    "Royal Challengers Bengaluru": "Bengaluru Bulls",
    "Kolkata Knight Riders": "Kolkata Knights",
    "Sunrisers Hyderabad": "Hyderabad Hawks",
    "Rajasthan Royals": "Rajasthan Raptors",
    "Delhi Capitals": "Delhi Dynamos",
    "Gujarat Titans": "Gujarat Gladiators",
    "Lucknow Super Giants": "Lucknow Lions",
    "Punjab Kings": "Punjab Panthers",
}

ABBR_MAP = {
    "CSK": "CHE", "MI": "MUM", "RCB": "BLR", "KKR": "KOL", "SRH": "HYD",
    "RR": "RAJ", "DC": "DEL", "GT": "GUJ", "LSG": "LKO", "PBKS": "PUN",
}

# Player name mapping actually applied to players.csv / players_alltime.csv
# (real -> fictional, IP-safe). Kept for audit; the CSV transform was done
# externally and validated (ratings/slots byte-identical, no real-name leaks).
PLAYER_MAP = {
    "AB de Villiers": "AB de Vylliers",
    "AM Ghazanfar": "AM Ghezanfar",
    "Aaron Finch": "Aeron Fynch",
    "Aarya Desai": "Aerya Disai",
    "Abdul Samad": "Abdol Semad",
    "Abhinandan Singh": "Abhynandan Syngh",
    "Abhinav Manohar": "Abhynav Menohar",
    "Abhinav Tejrana": "Abhynav Tijrana",
    "Abhishek Sharma": "Abhyshek Sherma",
    "Abishek Porel": "Abyshek Purel",
    "Adam Gilchrist": "Adem Gylchrist",
    "Adam Milne": "Adem Mylne",
    "Agit Agarkar": "Agyt Agerkar",
    "Aiden Markram": "Ayden Merkram",
    "Ajay Mandal": "Ajey Mendal",
    "Ajinkya Rahane": "Ajynkya Rehane",
    "Akash Deep": "Akesh Diep",
    "Akash Madhwal": "Akesh Medhwal",
    "Akash Singh": "Akesh Syngh",
    "Akeal Hosein": "Akial Husein",
    "Akshat Raghuwanshi": "Akshet Reghuwanshi",
    "Albie Morkel": "Albye Murkel",
    "Alfonso Thomas": "Alfunso Thumas",
    "Alzarri Joseph": "Alzerri Juseph",
    "Aman Khan": "Amen Khen",
    "Aman Rao": "Amen Reo",
    "Ambati Rayudu": "Ambeti Reyudu",
    "Amit Kumar": "Amyt Komar",
    "Amit Mishra": "Amyt Myshra",
    "Andre Russell": "Andri Rossell",
    "Andrew Flintoff": "Andriw Flyntoff",
    "Andrew Symonds": "Andriw Symunds",
    "Angkrish Raghuvanshi": "Angkrysh Reghuvanshi",
    "Aniket Verma": "Anyket Virma",
    "Anil Kumble": "Anyl Komble",
    "Anmolpreet Singh": "Anmulpreet Syngh",
    "Anrich Nortje": "Anrych Nurtje",
    "Anshul Kamboj": "Anshol Kemboj",
    "Anuj Rawat": "Anoj Rewat",
    "Anukul Roy": "Anokul Ruy",
    "Arjun Tendulkar": "Arjon Tindulkar",
    "Arshad Khan": "Arshed Khen",
    "Arshdeep Singh": "Arshdiep Syngh",
    "Arshin Kulkarni": "Arshyn Kolkarni",
    "Ashish Nehra": "Ashysh Nihra",
    "Ashok Sharma": "Ashuk Sherma",
    "Ashutosh Sharma": "Ashotosh Sherma",
    "Ashwani Kumar": "Ashweni Komar",
    "Atharva Ankolekar": "Atherva Ankulekar",
    "Atharva Taide": "Atherva Teide",
    "Auqib Dar": "Aoqib Der",
    "Auqib Nabi": "Aoqib Nebi",
    "Avesh Khan": "Avish Khen",
    "Axar Patel": "Axer Petel",
    "Ayush Badoni": "Ayosh Bedoni",
    "Ayush Mhatre": "Ayosh Mhetre",
    "Ayush Vartak": "Ayosh Vertak",
    "Azmatullah Omarzai": "Azmetullah Omerzai",
    "Ben Cutting": "Bin Cotting",
    "Ben Duckett": "Bin Dockett",
    "Ben Dwarshuis": "Bin Dwershuis",
    "Ben Stokes": "Bin Stukes",
    "Bhuvneshwar Kumar": "Bhovneshwar Komar",
    "Brad Hodge": "Bred Hudge",
    "Brendon McCullum": "Brindon McCollum",
    "Brett Lee": "Britt Lie",
    "Brijesh Sharma": "Bryjesh Sherma",
    "Brydon Carse": "Brydun Cerse",
    "Cameron Green": "Cemeron Grien",
    "Chama Milind": "Chema Mylind",
    "Chetan Sakariya": "Chitan Sekariya",
    "Chintal Gandhi": "Chyntal Gendhi",
    "Chris Gayle": "Chrys Geyle",
    "Chris Lynn": "Chrys Lyno",
    "Chris Morris": "Chrys Murris",
    "Connor Esterhuizen": "Cunnor Estirhuizen",
    "Cooper Connolly": "Cuoper Cunnolly",
    "Corbin Bosch": "Curbin Busch",
    "DJ Hussey": "DJ Hossey",
    "Daksh Kamra": "Deksh Kemra",
    "Dale Steyn": "Dele Stiyn",
    "Dan Lawrence": "Den Lewrence",
    "Daniel Lategan": "Deniel Letegan",
    "Daniel Vettori": "Deniel Vittori",
    "Danish Malewar": "Denish Melewar",
    "Daryl Mitchell": "Deryl Mytchell",
    "Dasun Shanaka": "Desun Shenaka",
    "David Miller": "Devid Myller",
    "David Warner": "Devid Werner",
    "Deepak Chahar": "Diepak Chehar",
    "Deepak Hooda": "Diepak Huoda",
    "Devdutt Padikkal": "Divdutt Pedikkal",
    "Devon Conway": "Divon Cunway",
    "Dewald Brevis": "Diwald Brivis",
    "Dhawal Kulkarni": "Dhewal Kolkarni",
    "Dhawan Rishi": "Dhewan Ryshi",
    "Dheeraj Kumar": "Dhieraj Komar",
    "Dhruv Jurel": "Dhrov Jorel",
    "Digvesh Rathi": "Dygvesh Rethi",
    "Dinesh Karthik": "Dynesh Kerthik",
    "Dirk Nannes": "Dyrk Nennes",
    "Donovan Ferreira": "Dunovan Firreira",
    "Doug Bollinger": "Duug Bullinger",
    "Dushmantha Chameera": "Doshmantha Chemeera",
    "Dwayne Bravo": "Dweyne Brevo",
    "Dwayne Smith": "Dweyne Smyth",
    "Eden Apple Tom": "Edin Appli Tum",
    "Eoin Morgan": "Euin Murgan",
    "Eshan Malinga": "Eshen Melinga",
    "Faf du Plessis": "Fef du Plissis",
    "Fazalhaq Farooqi": "Fezalhaq Ferooqi",
    "Finn Allen": "Fynn Allin",
    "Gautam Gambhir": "Geutam Gembhir",
    "Gerald Coetzee": "Girald Cuetzee",
    "Glenn Maxwell": "Glinn Mexwell",
    "Glenn Phillips": "Glinn Phyllips",
    "Graeme Smith": "Greeme Smyth",
    "Gurjapneet Singh": "Gorjapneet Syngh",
    "Gurnoor Brar": "Gornoor Brer",
    "Gus Atkinson": "Gos Atkynson",
    "Harbhajan Singh": "Herbhajan Syngh",
    "Hardik Pandya": "Herdik Pendya",
    "Harnoor Singh": "Hernoor Syngh",
    "Harpreet Brar": "Herpreet Brer",
    "Harsh Dubey": "Hersh Dobey",
    "Harshal Patel": "Hershal Petel",
    "Harshit Rana": "Hershit Rena",
    "Heinrich Klaasen": "Hiinrich Kleasen",
    "Himmat Singh": "Hymmat Syngh",
    "Imran Tahir": "Imren Tehir",
    "Irfan Pathan": "Irfen Pethan",
    "Irfan Umair": "Irfen Umeir",
    "Ishan Kishan": "Ishen Kyshan",
    "Ishant Sharma": "Ishent Sherma",
    "Izaz Sawariya": "Izez Sewariya",
    "JP Duminy": "JP Dominy",
    "Jack Edwards": "Jeck Edwerds",
    "Jacob Bethell": "Jecob Bithell",
    "Jacob Duffy": "Jecob Doffy",
    "Jacques Kallis": "Jecques Kellis",
    "Jake Fraser-McGurk": "Jeke Freser-McGork",
    "James Faulkner": "Jemes Feulkner",
    "Jamie Overton": "Jemie Ovirton",
    "Jamie Smith": "Jemie Smyth",
    "Jason Holder": "Jeson Hulder",
    "Jasprit Bumrah": "Jesprit Bomrah",
    "Jayant Yadav": "Jeyant Yedav",
    "Jaydev Unadkat": "Jeydev Unedkat",
    "Jesse Ryder": "Jisse Rydir",
    "Jhye Richardson": "Jhyi Rychardson",
    "Jikku Bright": "Jykku Bryght",
    "Jitesh Sharma": "Jytesh Sherma",
    "Jofra Archer": "Jufra Archir",
    "Jonny Bairstow": "Junny Beirstow",
    "Jordan Cox": "Jurdan Cux",
    "Jos Buttler": "Jus Bottler",
    "Josh Hazlewood": "Jush Hezlewood",
    "Josh Inglis": "Jush Inglys",
    "KC Cariappa": "KC Ceriappa",
    "KL Rahul": "KL Rehul",
    "KM Asif": "KM Asyf",
    "Kagiso Rabada": "Kegiso Rebada",
    "Kamindu Mendis": "Kemindu Mindis",
    "Kamlesh Nagarkoti": "Kemlesh Negarkoti",
    "Kane Williamson": "Kene Wylliamson",
    "Kanishk Chouhan": "Kenishk Chuuhan",
    "Karan Lal": "Keran Lel",
    "Karn Sharma": "Kern Sherma",
    "Kartik Sharma": "Kertik Sherma",
    "Kartik Tyagi": "Kertik Tyegi",
    "Karun Nair": "Kerun Neir",
    "Kevin Pietersen": "Kivin Pyetersen",
    "Khaleel Ahmed": "Kheleel Ahmid",
    "Kieron Pollard": "Kyeron Pullard",
    "Krains Fuletra": "Kreins Foletra",
    "Krunal Pandya": "Kronal Pendya",
    "Kuldeep Sen": "Koldeep Sin",
    "Kuldeep Yadav": "Koldeep Yedav",
    "Kumar Kartikeya": "Komar Kertikeya",
    "Kumar Kushagra": "Komar Koshagra",
    "Kumar Sangakkara": "Komar Sengakkara",
    "Kwena Maphaka": "Kwina Mephaka",
    "Kyle Jamieson": "Kyli Jemieson",
    "Lakshmipathy Balaji": "Lekshmipathy Belaji",
    "Lasith Malinga": "Lesith Melinga",
    "Lendl Simmons": "Lindl Symmons",
    "Lhuan-dre Pretorius": "Lhoan-dri Pritorius",
    "Liam Livingstone": "Lyam Lyvingstone",
    "Lockie Ferguson": "Luckie Firguson",
    "Luke Wood": "Loke Wuod",
    "Lungi Ngidi": "Longi Ngydi",
    "M Shahrukh Khan": "M Shehrukh Khen",
    "MS Dhoni": "MS Dhuni",
    "Macneil Noronha": "Mecneil Nuronha",
    "Madhav Tiwari": "Medhav Tywari",
    "Maheesh Theekshana": "Meheesh Thiekshana",
    "Mahela Jayawardene": "Mehela Jeyawardene",
    "Mahipal Lomror": "Mehipal Lumror",
    "Manan Vohra": "Menan Vuhra",
    "Manav Suthar": "Menav Sothar",
    "Mandeep Singh": "Mendeep Syngh",
    "Mangesh Yadav": "Mengesh Yedav",
    "Manimaran Siddharth": "Menimaran Syddharth",
    "Manisankar Murasingh": "Menisankar Morasingh",
    "Manish Pandey": "Menish Pendey",
    "Manoj Tiwary": "Menoj Tywary",
    "Marco Jansen": "Merco Jensen",
    "Marcus Stoinis": "Mercus Stuinis",
    "Matheesha Pathirana": "Metheesha Pethirana",
    "Matt Henry": "Mett Hinry",
    "Matthew Breetzke": "Metthew Brietzke",
    "Matthew Hayden": "Metthew Heyden",
    "Matthew Short": "Metthew Shurt",
    "Mayank Dagar": "Meyank Degar",
    "Mayank Markande": "Meyank Merkande",
    "Mayank Rawat": "Meyank Rewat",
    "Mayank Yadav": "Meyank Yedav",
    "Michael Bracewell": "Mychael Brecewell",
    "Michael Hussey": "Mychael Hossey",
    "Mitchell Johnson": "Mytchell Juhnson",
    "Mitchell Marsh": "Mytchell Mersh",
    "Mitchell McClenaghan": "Mytchell McClinaghan",
    "Mitchell Owen": "Mytchell Owin",
    "Mitchell Santner": "Mytchell Sentner",
    "Mitchell Starc": "Mytchell Sterc",
    "Moeen Ali": "Mueen Aly",
    "Mohammad Nabi": "Muhammad Nebi",
    "Mohammed Shami": "Muhammed Shemi",
    "Mohammed Siraj": "Muhammed Syraj",
    "Mohd Izhar": "Muhd Izher",
    "Mohit Rathee": "Muhit Rethee",
    "Mohit Sharma": "Muhit Sherma",
    "Mohsin Khan": "Muhsin Khen",
    "Money Grewal": "Muney Griwal",
    "Morne Morkel": "Murne Murkel",
    "Mujeeb Ur Rahman": "Mojeeb Ur Rehman",
    "Mukesh Choudhary": "Mokesh Chuudhary",
    "Mukesh Kumar": "Mokesh Komar",
    "Mukul Choudhary": "Mokul Chuudhary",
    "Munaf Patel": "Monaf Petel",
    "Murali Vijay": "Morali Vyjay",
    "Murugan Ashwin": "Morugan Ashwyn",
    "Musheer Khan": "Mosheer Khen",
    "Mustafizur Rahman": "Mostafizur Rehman",
    "Muttiah Muralitharan": "Mottiah Moralitharan",
    "Naman Dhir": "Neman Dhyr",
    "Naman Ojha": "Neman Ojhe",
    "Naman Tiwari": "Neman Tywari",
    "Nandre Burger": "Nendre Borger",
    "Nathan Coulter-Nile": "Nethan Cuulter-Nyle",
    "Nathan Ellis": "Nethan Ellys",
    "Nathan Smith": "Nethan Smyth",
    "Nehal Wadhera": "Nihal Wedhera",
    "Nicholas Pooran": "Nycholas Puoran",
    "Nishant Sindhu": "Nyshant Syndhu",
    "Nitish Kumar Reddy": "Nytish Komar Riddy",
    "Nitish Rana": "Nytish Rena",
    "Noor Ahmad": "Nuor Ahmed",
    "Nuwan Thushara": "Nowan Thoshara",
    "Onkar Tarmale": "Onker Termale",
    "Parthiv Patel": "Perthiv Petel",
    "Pat Cummins": "Pet Commins",
    "Pathum Nissanka": "Pethum Nyssanka",
    "Paul Collingwood": "Peul Cullingwood",
    "Phil Salt": "Phyl Selt",
    "Piyush Chawla": "Pyyush Chewla",
    "Prabhsimran Singh": "Prebhsimran Syngh",
    "Praful Hinge": "Preful Hynge",
    "Pragyan Ojha": "Pregyan Ojhe",
    "Prashant Solanki": "Preshant Sulanki",
    "Prashant Veer": "Preshant Vier",
    "Prasidh Krishna": "Presidh Kryshna",
    "Praveen Dubey": "Preveen Dobey",
    "Praveen Kumar": "Preveen Komar",
    "Prince Yadav": "Prynce Yedav",
    "Prithvi Raj": "Prythvi Rej",
    "Prithvi Shaw": "Prythvi Shew",
    "Priyansh Arya": "Pryyansh Arye",
    "Pyla Avinash": "Pyle Avynash",
    "Quinton de Kock": "Qointon de Kuck",
    "R Bhatia": "R Bhetia",
    "RP Singh": "RP Syngh",
    "RS Ambrish": "RS Ambrysh",
    "Rachin Ravindra": "Rechin Revindra",
    "Raghu Sharma": "Reghu Sherma",
    "Rahmanullah Gurbaz": "Rehmanullah Gorbaz",
    "Rahul Chahar": "Rehul Chehar",
    "Rahul Dravid": "Rehul Drevid",
    "Rahul Tewatia": "Rehul Tiwatia",
    "Rahul Tripathi": "Rehul Trypathi",
    "Raj Bawa": "Rej Bewa",
    "Raj Limbani": "Rej Lymbani",
    "Rajat Patidar": "Rejat Petidar",
    "Rajvardhan Hangargekar": "Rejvardhan Hengargekar",
    "Ramakrishna Ghosh": "Remakrishna Ghush",
    "Ramandeep Singh": "Remandeep Syngh",
    "Rashid Khan": "Reshid Khen",
    "Rasikh Salam": "Resikh Selam",
    "Ravi Bishnoi": "Revi Byshnoi",
    "Ravi Singh": "Revi Syngh",
    "Ravichandran Ashwin": "Revichandran Ashwyn",
    "Ravichandran Smaran": "Revichandran Smeran",
    "Ravindra Jadeja": "Revindra Jedeja",
    "Richard Gleeson": "Rychard Glieson",
    "Ricky Ponting": "Rycky Punting",
    "Riley Meredith": "Ryley Miredith",
    "Rinku Singh": "Rynku Syngh",
    "Rishabh Pant": "Ryshabh Pent",
    "Ritik Tada": "Rytik Teda",
    "Riyan Parag": "Ryyan Perag",
    "Robin Minz": "Rubin Mynz",
    "Robin Uthappa": "Rubin Utheppa",
    "Rohit Sharma": "Ruhit Sherma",
    "Romario Shepherd": "Rumario Shipherd",
    "Ross Taylor": "Russ Teylor",
    "Rovman Powell": "Ruvman Puwell",
    "Ruchit Ahir": "Rochit Ahyr",
    "Ruturaj Gaikwad": "Roturaj Geikwad",
    "Ryan McLaren": "Ryen McLeren",
    "Ryan Rickelton": "Ryen Ryckelton",
    "S Badrinath": "S Bedrinath",
    "Sachin Tendulkar": "Sechin Tindulkar",
    "Sahil Parakh": "Sehil Perakh",
    "Sai Kishore": "Sei Kyshore",
    "Sai Sudharsan": "Sei Sodharsan",
    "Sakib Hussain": "Sekib Hossain",
    "Salil Arora": "Selil Arura",
    "Salman Nizar": "Selman Nyzar",
    "Sam Curran": "Sem Corran",
    "Sameer Rizvi": "Semeer Ryzvi",
    "Sandeep Sharma": "Sendeep Sherma",
    "Sanju Samson": "Senju Semson",
    "Sanvir Singh": "Senvir Syngh",
    "Sarfaraz Khan": "Serfaraz Khen",
    "Sarthak Ranjan": "Serthak Renjan",
    "Satvik Deswal": "Setvik Diswal",
    "Sean Abbott": "Sian Abbutt",
    "Sediqullah Atal": "Sidiqullah Atel",
    "Shahbaz Ahmed": "Shehbaz Ahmid",
    "Shahbaz Nadeem": "Shehbaz Nedeem",
    "Shakib Al Hasan": "Shekib Al Hesan",
    "Shane Warne": "Shene Werne",
    "Shane Watson": "Shene Wetson",
    "Shardul Thakur": "Sherdul Thekur",
    "Shashank Singh": "Sheshank Syngh",
    "Shaun Marsh": "Sheun Mersh",
    "Shaun Pollock": "Sheun Pullock",
    "Sherfane Rutherford": "Shirfane Rotherford",
    "Shikhar Dhawan": "Shykhar Dhewan",
    "Shimron Hetmyer": "Shymron Hitmyer",
    "Shivam Dube": "Shyvam Dobe",
    "Shivam Mavi": "Shyvam Mevi",
    "Shivam Shukla": "Shyvam Shokla",
    "Shivang Kumar": "Shyvang Komar",
    "Shreyas Gopal": "Shriyas Gupal",
    "Shreyas Iyer": "Shriyas Iyir",
    "Shubham Dubey": "Shobham Dobey",
    "Shubman Gill": "Shobman Gyll",
    "Siddarth Yadav": "Syddarth Yedav",
    "Siddharth Kaul": "Syddharth Keul",
    "Simarjeet Singh": "Symarjeet Syngh",
    "Sohail Tanvir": "Suhail Tenvir",
    "Sourav Ganguly": "Suurav Genguly",
    "Spencer Johnson": "Spincer Juhnson",
    "Srikar Bharat": "Srykar Bherat",
    "Steve Smith": "Stive Smyth",
    "Sunil Narine": "Sonil Nerine",
    "Suresh Raina": "Soresh Reina",
    "Suryakumar Yadav": "Soryakumar Yedav",
    "Suryansh Shedge": "Soryansh Shidge",
    "Sushant Mishra": "Soshant Myshra",
    "Suyash Sharma": "Soyash Sherma",
    "Swapnil Singh": "Swepnil Syngh",
    "Swastik Chikara": "Swestik Chykara",
    "T Natarajan": "T Netarajan",
    "Tanay Thyagarajan": "Tenay Thyegarajan",
    "Tanush Kotian": "Tenush Kutian",
    "Taskin Ahmed": "Teskin Ahmid",
    "Tejas Baroka": "Tijas Beroka",
    "Tejasvi Dahiya": "Tijasvi Dehiya",
    "Thisara Perera": "Thysara Pirera",
    "Tilak Varma": "Tylak Verma",
    "Tillakaratne Dilshan": "Tyllakaratne Dylshan",
    "Tim David": "Tym Devid",
    "Tim Seifert": "Tym Siifert",
    "Tom Banton": "Tum Benton",
    "Travis Head": "Trevis Hiad",
    "Trent Boult": "Trint Buult",
    "Tripurana Vijay": "Trypurana Vyjay",
    "Tristan Stubbs": "Trystan Stobbs",
    "Tushar Deshpande": "Toshar Dishpande",
    "Tushar Raheja": "Toshar Reheja",
    "Umesh Yadav": "Umish Yedav",
    "Umran Malik": "Umren Melik",
    "Urvil Patel": "Urvyl Petel",
    "Utkarsh Singh": "Utkersh Syngh",
    "VVS Laxman": "VVS Lexman",
    "Vaibhav Arora": "Veibhav Arura",
    "Vaibhav Sooryavanshi": "Veibhav Suoryavanshi",
    "Vansh Bedi": "Vensh Bidi",
    "Varun Aaron": "Verun Aeron",
    "Varun Chakravarthy": "Verun Chekravarthy",
    "Venkatesh Iyer": "Vinkatesh Iyir",
    "Vicky Ostwal": "Vycky Ostwel",
    "Vignesh Puthur": "Vygnesh Pothur",
    "Vihaan Malhotra": "Vyhaan Melhotra",
    "Vijay Shankar": "Vyjay Shenkar",
    "Vijaykumar Vyshak": "Vyjaykumar Vyshek",
    "Vinay Kumar": "Vynay Komar",
    "Vipraj Nigam": "Vypraj Nygam",
    "Virat Kohli": "Vyrat Kuhli",
    "Virender Sehwag": "Vyrender Sihwag",
    "Vishal Nishad": "Vyshal Nyshad",
    "Vishnu Vinod": "Vyshnu Vynod",
    "Wahidullah Zadran": "Wehidullah Zedran",
    "Wanindu Hasaranga": "Wenindu Hesaranga",
    "Waqar Salamkheil": "Weqar Selamkheil",
    "Washington Sundar": "Weshington Sondar",
    "Wiaan Mulder": "Wyaan Molder",
    "Will Jacks": "Wyll Jecks",
    "Will Sutherland": "Wyll Sotherland",
    "Wriddhiman Saha": "Wryddhiman Seha",
    "Xavier Bartlett": "Xevier Bertlett",
    "Yash Dayal": "Yesh Deyal",
    "Yash Dhull": "Yesh Dholl",
    "Yash Raj Punja": "Yesh Rej Ponja",
    "Yash Thakur": "Yesh Thekur",
    "Yashasvi Jaiswal": "Yeshasvi Jeiswal",
    "Yudhvir Singh": "Yodhvir Syngh",
    "Yusuf Pathan": "Yosuf Pethan",
    "Yuvraj Singh": "Yovraj Syngh",
    "Yuzvendra Chahal": "Yozvendra Chehal",
    "Zaheer Khan": "Zeheer Khen",
    "Zak Foulkes": "Zek Fuulkes",
    "Zeeshan Ansari": "Zieshan Anseri",
}

# Files that reference team names as plain strings (the player CSVs are
# transformed separately and already contain the fictional names).
TEAM_TEXT_FILES = [
    ENGINE / "players_data.py",
    ENGINE / "sim" / "live_match.py",
    ROOT / "mobile" / "src" / "constants" / "theme.ts",
    ROOT / "webapp" / "index.html",
    ROOT / "docs" / "mockups" / "phase1-mockups.html",
    ROOT / "legacy" / "ui_server.py",
    ROOT / "tests" / "conftest.py",
    ROOT / "tests" / "test_league_state_extra.py",
    ROOT / "tests" / "test_serialization.py",
    ROOT / "tests" / "test_draft.py",
    ROOT / "backend" / "tests" / "careers" / "test_match_history.py",
    ROOT / "backend" / "tests" / "careers" / "test_career_routes.py",
    ROOT / "backend" / "tests" / "season" / "test_season_routes.py",
    ROOT / "backend" / "tests" / "live_match" / "test_live_match_routes.py",
    ROOT / "backend" / "tests" / "auth" / "test_auth_routes.py",
]


def _replace_teams(text: str) -> str:
    for old, new in TEAM_MAP.items():
        text = text.replace(old, new)
    for old, new in ABBR_MAP.items():
        for q in ("'", '"'):
            text = text.replace(f"{q}{old}{q}", f"{q}{new}{q}")
    return text


def apply_team_renames(write: bool) -> None:
    for path in TEAM_TEXT_FILES:
        if not path.exists():
            print(f"  (skip, missing) {path}")
            continue
        original = path.read_text()
        updated = _replace_teams(original)
        if updated != original:
            print(f"  team-renamed {path.relative_to(ROOT)}")
            if write:
                path.write_text(updated)


def apply_player_roster_renames(write: bool) -> None:
    """Re-apply PLAYER_MAP to the quoted roster names in players_data.py."""
    path = ENGINE / "players_data.py"
    text = path.read_text()
    # Longest names first so a short name isn't a substring of a longer one.
    for real in sorted(PLAYER_MAP, key=len, reverse=True):
        fict = PLAYER_MAP[real]
        for q in ("'", '"'):
            text = text.replace(f"{q}{real}{q}", f"{q}{fict}{q}")
    print(f"  roster-renamed players_data.py")
    if write:
        path.write_text(text)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--apply", action="store_true", help="rewrite files in place")
    parser.add_argument("--check", action="store_true", help="print mappings only")
    args = parser.parse_args()

    print(f"Teams: {len(TEAM_MAP)}  Players: {len(PLAYER_MAP)}")
    print("\nApplying team renames:")
    apply_team_renames(write=args.apply)
    print("Applying player roster renames:")
    apply_player_roster_renames(write=args.apply)
    if not args.apply:
        print("\n(dry run — pass --apply to write)")


if __name__ == "__main__":
    main()
